services:
    _defaults:
        autowire: true
        autoconfigure: true

    JL\IbexaEnhancedMigrations\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Entity,Tests,IbexaEnhancedMigrationsBundle.php}'
